### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by t-young31** [UCL/TDMS#12]
Perhaps [spdlog](https://github.com/gabime/spdlog)? Suggestions welcome!

**Comment by giordano** [comment]
I don't really have much experience with logging in C++.  Out of curiosity, what do you plan to use it for?

**Comment by t-young31** [comment]
There are currently lots of commented out print lines (e.g. [here](https://github.com/UCL/TDMS/blob/2b8d585d9de8fb1974f18cbc201f277a0955ed10/iterater/iterater_OMP_FDTD.cpp#L1182)), that might be nice to convert to logging statements for debugging etc(?)
