### ISSUE TITLE
`pip3 install h5py` MacOS-python 3.11 compatibility

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#183]
Installs of `h5py` on MacOS are (at the time of writing) broken due to an upstream bug.

We have #182 which forces an install of Python 3.10 which bypasses this issue which is [unique to Python 3.11 installs](https://github.com/samcunliffe/h5py-macos-ghrunner-mwe/actions/runs/3456736301) of `h5py`.

Opening this issue as a reminder for us to check back in on this and hopefully remove the strict Python 3.10 requirement.

**Comment by samcunliffe** [comment]
@dpshelio found [h5py/issues/2146](https://github.com/h5py/h5py/issues/2146) which looks like our upstream bug.
