### ISSUE TITLE
Update to `iteratefdtd_matrix`

### ISSUE THREAD

**Issue by prmunro** [UCL/TDMS#208]
I have made the updates to iteratefdtd_matrix, which will change the mat file which is used as input to TDMS (for my reference, iteratefdtd_matrix was modified in in distribute_arc_01/newinput). The modified file is attached. Here is a description of the changes. Test cases have also been uploaded. 
[iteratefdtd_matrix.zip](https://github.com/UCL/TDMS/files/10286980/iteratefdtd_matrix.zip)
[arc_18.zip](https://github.com/UCL/TDMS/files/10286984/arc_18.zip)
[arc_17.zip](https://github.com/UCL/TDMS/files/10286985/arc_17.zip)
[summary.txt](https://github.com/UCL/TDMS/files/10286986/summary.txt)

**

## ~Blocked by~

* ~#210~
* :heavy_check_mark: #215 

## Potential to conflict with

* the rest of #63

**Comment by samcunliffe** [comment]
## Modifications made to the way the illumination is specified

`iteratefdtd_matrix.m` will create an output file with the following properties, depending on whether a time-domain or pulsed illumination is specified.

There are methods by which the illumination can be specified:

1. When no illumination file is passed to iteratefdtd_matrix as an input parameter, the field can only be pulsed and is specified through the filenames efname and hfname in the input file. There are two options within this case:
   1. Non-empty efname and hfname are specified, resulting in one or more of Isource, Jsource and Ksource being non-empty. tdfield will contain exi and eyi, which will both be empty.
   2. Empty efname and hfname are specified, resulting in all of Isource, Jsource and Ksource being empty. tdfield will contain exi and eyi, which will both be empty.

or

2. When an illumination file containing elements Isource, Jsource and Ksource is specified, created by a call to iteratefdtd_matrix with operation illsetup, illumination will only be pulsed. One or more of Isource, Jsource and Ksource shoudl be non-empty, although it is possible for all to be empty if the user specified empty values for efname and hfname. tdfield will contain exi and eyi, which will both be empty.

or

3. When an illumination file containing fields exi and eyi is specified, a time-domain illumination is specified. tdfield will
contain a copy of exi and eyi. There are two options with regards to pulsed fields:
   1. The user specifies empty efname and hfname, in which case no pulsed field is specified. This is the expected case. Isource, Jsource and Ksource will be empty.
   2. The user specifies non-empty efname and hfname, in which case on or more of Isource, Jsource and Ksource will be non-empty.


Test cases for the above are outlined in `run_pstd_bscan.m`

Whenever one of Isource, Jsource or Ksource is non-empty, the associated field update lines in the main loop need to be executed.

Whenever Isource, Jsource and Ksource are all non-empty, meaning that a pulsed field has not been specified, output complex amplitudes should not be normalised by the pulsed field spectrum shape. In my version of TDMS, this would mean not performing the following lines of code:

```c++
   normaliseVolume(ExR,ExI,EyR,EyI,EzR,EzI,
		    pind_il,pind_iu,
		    pind_jl,pind_ju,
		    pind_kl,pind_ku,
		    E_norm_an);

    normaliseVolume(HxR,HxI,HyR,HyI,HzR,HzI,
		    pind_il,pind_iu,
		    pind_jl,pind_ju,
		    pind_kl,pind_ku,
		    H_norm_an);
		    
  normaliseVertices( camplitudesR[ifx], camplitudesI[ifx],  
			 vertices, nvertices,
			 components, ncomponents,
			 E_norm[ifx], H_norm[ifx]);

     normaliseSurface( surface_EHr[ifx], surface_EHi[ifx],  
			surface_vertices, n_surface_vertices, E_norm[ifx], H_norm[ifx]);
```
		    



## Modifications made to how the choice of PSTD/FDTD algorithm is chosen

The user can specify a variable usecd in the input file which should have the following implications:

* `usecd=1`, means that the FDTD algorithm is used
* `usecd=0`, means that the PSTD algorithm is used

If the user does not specify the value of usecd in the input file, it is set to 1 by default.

The `iteratefdtd_matrix` script now changes where it calculates the input field is `usecd=0`, this was previously done by the user which was prone to error (test cases need to be generated for this).

## Modifications for choosing interpolation method	

There is already a variable created called `intmethod`, which has the following meaning:

* `intmethod=1`, use cubic interpolation
* `intmethod=2`, use band limited

The default is `intmethod=1`

I have not created test cases for this as it is already included in `iteratefdtd_matrix.m`.

**Comment by willGraham01** [comment]
Having done a read-through and a quick exploration of the new files, it looks like this can be split into two independent tasks (from the view of the codebase):

### #216

These changes are rather self contained, and do not require any major reworking of the current test framework or how `tdms` behaves on the command line. _Where_ in the codebase these changes occur will be in either `execute_simulation` or `simulation.execute`, depending on post or pre #215.

### #217

These changes are going to touch multiple files at once, _and_ require that we update the system test framework since we no longer need to read in command-line options.

**Comment by samcunliffe** [comment]
[ Removing myself because I don't deserve any of the credit for #253 ]

**Comment by willGraham01** [comment]
@prmunro Hi Peter - just in the process of reconciling the `iteratefdtd_matrix` function here and the one on `main`. In the process, I found a typo on line 1027 of the version you uploaded here:
```matlab
eval(sprintf('source_field = %s(X,Y,Z=delta.z/2);',efname ));
```
there's an "=" in "Z=delta.z/2" which should be a "-". You might want to quickly update your own local version of `iteratefdtd_matrix`.

**Comment by willGraham01** [comment]
Thanks for sending this through @prmunro - I'll begin making the updates here. It appears as though the arc_19.zip link is to an empty zip folder though?
