### ISSUE TITLE
`iwave_` bootstrapping variables are unneccessary

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#214]
The variables used in the call to `extractPhasorsPlane` in `iterator.cpp` are never referenced again in the code, are not outputs that are written to the file, and are not used by any other structures.

At a functional level, this means that they currently serve no purpose in the codebase and we should be able to remove them without issue. However it looks like this is a remnant of a feature that was partially implemented, and then abandoned. Most likely functionality to allow the user to extract phasors on a pre-defined plane - @prmunro can you remember anything about this?

**Comment by prmunro** [comment]
Thanks @willGraham01 , I had forgotten about that line of code. That is legacy code that served a purpose in very early version of the code and, as you've noticed, is no longer used. This can be safely removed from TDMS. 

However, it does bring up an issue I hadn't previously considered. in particular, in some applications it would be useful to extract complex amplitudes from where the field is actually sampled (i.e., without interpolation). Let's discuss this on the 24th.
