### ISSUE TITLE
`array_ind` scoping issues

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#226]
In the `Jsource` loop, the `!inputs.params.is_multilayer`-logical statement occurs within the first `k < inputs.K1.index` conditional statement. 

This is inconsistent with the other loops, where the former is conducted prior to entering the latter conditional block. Additionally, the `array_ind` variable that is assigned in this conditional block is [used again on line 181](https://github.com/UCL/TDMS/blob/10a41b17c6e993f4265c6929366d4f54261f0edb/tdms/src/simulation_manager/source_term_updates.cpp#L150-L181) - despite the fact that it might not actually have been set! 

The logical inconsistency can be seen in [Jsource loop](https://github.com/UCL/TDMS/blob/10a41b17c6e993f4265c6929366d4f54261f0edb/tdms/src/simulation_manager/source_term_updates.cpp#L150-L158) compared to the [Isource loop](https://github.com/UCL/TDMS/blob/10a41b17c6e993f4265c6929366d4f54261f0edb/tdms/src/simulation_manager/source_term_updates.cpp#L25-L34), for example.

**Comment by prmunro** [comment]
I suggest to move the assignment of array_ind to outside the 

if (k < (inputs.K1.index) ||
            inputs.params.dimension == Dimension::TRANSVERSE_MAGNETIC) 

statement.
