### ISSUE TITLE
Adding contributors to doi

### ISSUE THREAD

**Issue by prmunro** [UCL/TDMS#256]
Here are the additional contributors to add to the doi:

Professor Peter Török
Nanyang Technical University
Singapore
peter.torok@ntu.edu.sg

Professor Emmanouil Kriezis
Aristotle University of Thessaloniki
Greece
mkriezis@auth.gr

Let me know if any further information is needed.

**Comment by samcunliffe** [comment]
Thanks Peter! I've updated #84, that actually should be reviewed by you to check you're happy with everything. I've also given the software a "title".
