### ISSUE TITLE
Enable merge queues for PRs to `main`.

### ISSUE THREAD

**Issue by samcunliffe** [UCL/TDMS#287]
New GH feature.
* [Announcement blog](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/).
* [Docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue).

**Comment by samcunliffe** [comment]
@willGraham01 fyi ☝️ this is the setting to revert if it all goes horribly wrong.

**Comment by willGraham01** [comment]
> @willGraham01 fyi point_up this is the setting to revert if it all goes horribly wrong.

I've added #262 to the merge queue as our first test-case :grin:
