### ISSUE TITLE
Consistently write "bandlimited interpolation" over "band-limited interpolation"

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#298]
As requested by @samcunliffe here: https://github.com/UCL/TDMS/pull/262/files#r1190830613

Scientific language uses "bandlimited interpolation" over "band-limited interpolation" (no hyphen/dash). 

So a repository-wide find and replace needs to be conducted.

**Comment by willGraham01** [comment]
This was closed with #262, not sure why it didn't auto-close when linked.

**Comment by giordano** [comment]
>  not sure why it didn't auto-close when linked.

Because it wasn't linked?

![image](https://github.com/UCL/TDMS/assets/765740/ea771f1c-c1fa-40be-ba47-5955217ea183)

**Comment by willGraham01** [comment]
It was linked in #299, which then got merged into #262.

Although saying that, #299 looks like GitHub didn't auto-link this issue from the PR text anyway

**Comment by giordano** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

> **Note**: The special keywords in a pull request description are interpreted when the pull request targets the repository's *default* branch. However, if the PR's base is *any other branch*, then these keywords are ignored, no links are created and merging the PR has no effect on the issues. **If you want to link a pull request to an issue using a keyword, the PR must be on the default branch**.

Emphasis not mine.

**Comment by samcunliffe** [comment]
Yeah. Also, it's not solved because it's not solved.
Like on `main`.
