### ISSUE TITLE
Add more system tests

### ISSUE THREAD

**Issue by t-young31** [UCL/TDMS#30]
Currently there are only PSTD tests, at least one FDTD test should also be included, and others.

- [ ] FDTD
- [x] steadystate = true
- [x] exdetIntegral = true
- [x] exi is present

**Comment by samcunliffe** [comment]
Kinda high priority if it's blocking the refactor.

**Comment by prmunro** [comment]
Here is a test of steady state behaviour. The script arc_08/run_pstd_bscan.m generates two output files:

arc_08/out/pstd_sph_steady.mat
arc_08/out/pstd_fs_steady.mat

which can be considered the correct result. Note that issue https://github.com/UCL/TDMS/issues/93#issue-1374674142 needs to be resolved before the TDMS version of the code will produce output that agrees with these files. 

run_pstd_bscan.m requires a particular directory structure as evident from the addpath statements. 

The test can be downloaded from UCL dropbox (too large for direct upload):

    You will need the claim passcode '5d0a7097' 
to retrieve the file(s).  

    It is up to you to scan the downloaded file(s) for viruses. Most anti-virus applications will do this automatically, but you should check.

    The file(s) will be available for 10 days.


*** Details for retrieval: ***
    
pick-up URL: https://wwwapps-live.ucl.ac.uk/cgi-bin/dropbox/dropbox-https.cgi?state=pickup_info&id=3d2c36cb
claim id: 3d2c36cb
file basename: arc_08.zip
file length: 563336149
file content_type: application/zip
description:

**Comment by samcunliffe** [comment]
Thanks! I have it. 

Files arc01-03.zip were uploaded to zenodo and the [system tests grab the data then run tdms over them](https://github.com/UCL/TDMS/blob/main/tdms/tests/system/test_arc01.py#L9).

**Comment by samcunliffe** [comment]
Wall times:
```
py.test ../test_arc08.py  6251.60s user 305.00s system 722% cpu 15:07.20 total
py.test ../test_arc03.py  1241.86s user 55.81s system 564% cpu 3:49.90 total
```

Running tdms over arc08 (in/pstd_fs_steady.mat and in/pstd_sph_fs_steady.mat) is a lot slower than, for example, [arc03](https://github.com/UCL/TDMS/blob/main/tdms/tests/system/test_arc03.py). Probably this is expected(?)  Does it make sense to down-sample here? I mean, just for speeding up the automatic test. Or can we live with this?

**Comment by prmunro** [comment]
I have generated another test (arc_09) which makes use of the exdetintegral functionality. Details for download are:


    The recipient(s) will need the claim passcode '70c805f6' 
to retrieve the file(s).  

    It is up to the recipient(s) to scan the downloaded file(s) for viruses. Most anti-virus applications will do this automatically, but this should be checked.

    The file(s) will be available for 10 days.


*** Details for retrieval: ***
    
pick-up URL: https://wwwapps-live.ucl.ac.uk/cgi-bin/dropbox/dropbox-https.cgi?state=pickup_info&id=eac2a3f
claim id: eac2a3f
file basename: arc_09.zip
file length: 125174939
file content_type: application/zip
description:

**Comment by prmunro** [comment]
Here is a test where exi is present. 
[arc_10.zip](https://github.com/UCL/TDMS/files/9585521/arc_10.zip)
