### ISSUE TITLE
Reading complex-valued arrays from HDF5 files.

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#335]
Pertains to #70 and #285.

There is no support within HDF5 for a complex number datatype. The norm for both MATLAB and `h5py` seems to be to create a custom `H5COMPOUND` datatype that encodes the real and imaginary parts separately, and to save the data in this format.

This means we need to adapt to this when reading our input file, for example when reading in the `DTilde` array. By the looks of things, when handling a `.mat` input we will need to define a compound datatype that can handle the format below:
![image](https://github.com/UCL/TDMS/assets/32364977/08740e1d-55eb-4835-abd1-2f21add86c38)

IE a compound datatype that has a `real` and `imag` member.

**Comment by samcunliffe** [comment]
Solved with #343.
