### ISSUE TITLE
Test compilation for Windows

### ISSUE THREAD

**Issue by t-young31** [UCL/TDMS#43]
TDMS has only been built on MacOS and linux thus far. We need to check this is also possible on Windows

**Comment by giordano** [comment]
Reading the docs of [`matlab-actions/setup-matlab`](https://github.com/matlab-actions/setup-matlab) it wasn't clear to me whether it supports Windows (or macOS), maybe we can just try to enable those platforms and see what happens, maybe it just works?

**Comment by t-young31** [comment]
Lets give it a go! [This comment](https://github.com/matlab-actions/setup-matlab/issues/18#issuecomment-1006990188) suggests it might be possible
