### ISSUE TITLE
More examples/demonstrations

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#58]
Currently there is only one piece of example/demonstration code, `examples/arc-01`.
It would be beneficial for both documentation and testing purposes if we had additional examples to hand, and additionally emphasised calls to the TDMS executable rather than the supporting MATLAB scripts:
- Suppressing the MATLAB GUI from opening when setting up the input files, and using a shell script to avoid hiding the call to tdms within MATLAB's `eval()`?
- Save visualisations of the output to files, rather than opening them as figures in MATLAB

**Comment by prmunro** [comment]
@willGraham01 , I have previously created tests arc_02 to arc_05 (arc_06 and arc_07 were used as demonstrators or to generate figures for the interpolation doc). arc_08 is the most recent test case. arc_05 is included in the unit test cases according to https://github.com/UCL/TDMS/pull/37#issuecomment-1199123565. 

Can you find references to tests arc_02, arc_03 and arc_04 anywhere?

**Comment by willGraham01** [comment]
We now have 14 tests for both free space and an obstacle present
