### ISSUE TITLE
Odd behaviour in `interpolate.cpp`

### ISSUE THREAD

**Issue by willGraham01** [UCL/TDMS#60]
# Odd behaviour in `interpolate.cpp` [Related to #44] 

Several functions in `interpolate.cpp` seem to have redundant `for` loops, and mismatches between the function doc-string and what the function actually does.
Looking at [`interpolateFieldCentralE_TE`](https://github.com/UCL/TDMS/blob/526987ce4ba47d982e90787b6e4e67af94dfb353/tdms/src/interpolate.cpp#L115-L176) for example:
- An error is thrown unless `k_u` $\leq 0\leq$ `k_l`, which is in contrast to what the docstring claims the acceptable values of `k_l` ( $\geq 2$ ) and `k_u` ( $\leq$ `K` $-2$) are.
- The variables `i_u`, `j_u`, `k_u` have intent[out], but are never assigned to, not pointers, and not returned.
- `for(k=k_l; k<=k_u; k++)` only executes when `k_u` $\leq 0\leq$ `k_l` due to the previous error checks, and so `k` can only take the value 0.

The same things occur in `interpolateFieldCentralE_TM`, `interpolateFieldCentralH_TE`, and `interpolateFieldCentralH_TM`.

If the intended behaviour is what's listed in the doc-strings; the code needs to be changed and we need to check whether the result of any demonstration code or tests _depend_ on then also changes, due to dependence on these functions.
If what's currently in the code is the intended behaviour, it looks like it can be made more readable and the doc-strings updated to match.

**Comment by t-young31** [comment]
assume this will be closed by #44  ?!

**Comment by willGraham01** [comment]
> assume this will be closed by #44 ?!

Should be. Although if we want to play around with allowing interpolation to use the field in the PML, something similar might pop up again - but we can deal with that when we get to it!
