### ISSUE TITLE
Add a github action to build macos

### ISSUE THREAD

**Issue by samcunliffe** [UCL/TDMS#78]
[Placeholder issue, we might want to reject]

We are currently building windows and linux, worth to add macos? Mention this because @samcunliffe had some strange issues compiling. If this is a workflow we expect of future users/students, we probably want to test it.

On the other hand, perhaps this is a waste of time.

**Comment by giordano** [comment]
The first commit in #48 added macOS as well, but then we gave up on that. I think something wasn't quite working but we didn't push it because it wasn't high priority, but I don't remember the details.
