### ISSUE TITLE
Bug in steady state part of code

### ISSUE THREAD

**Issue by prmunro** [UCL/TDMS#93]
Hi @samcunliffe  and @willGraham01, in the process of preparing a test case for the steady state option, I found an error in my version (and therefore the TDSM version) of the code. What’s the best was to make this change on the TDSM repository. It’s a relatively simple update

The code appears in the vicinity of line 5900 in the old version of the code as follows, though let me know if you want me to make this change directly in the code. This code is now in the vicinity of line 5762 in the TDMS repo, and has been changed. Although the changes in the old code will transfer easily to the new code.

Incorrect version 
```c++
     if(sourcemode==sm_steadystate){
	extractPhasorENorm(&E_norm_an, fte, tind, *omega_an, *dt, Nsteps);
	extractPhasorHNorm(&H_norm_an, fth, tind, *omega_an, *dt, Nsteps);
	for(int ifx=0;ifx<N_f_ex_vec;ifx++){
	  extractPhasorENorm(&E_norm[ifx], fte, tind, f_ex_vec[ifx]*2*dcpi, *dt, Nsteps);
	  extractPhasorHNorm(&H_norm[ifx], fth, tind, f_ex_vec[ifx]*2*dcpi, *dt, Nsteps);
	}
```

Correct version
```c++
      if(sourcemode==sm_steadystate){
	if( (tind % Nsteps)==0 ){
	  E_norm_an = 0.;
	  H_norm_an = 0.;
	}
	extractPhasorENorm(&E_norm_an, fte, tind % Nsteps, *omega_an, *dt, Nsteps);
	extractPhasorHNorm(&H_norm_an, fth, tind % Nsteps, *omega_an, *dt, Nsteps);
	//fprintf(stderr,"Enorm = %e+i%e, fte=%e, tinf=%d, %d\n", real(E_norm_an), imag(E_norm_an), fte, tind % Nsteps, Nsteps);
	for(int ifx=0;ifx<N_f_ex_vec;ifx++){
	  extractPhasorENorm(&E_norm[ifx], fte, tind % Nsteps, f_ex_vec[ifx]*2*dcpi, *dt, Nsteps);
	  extractPhasorHNorm(&H_norm[ifx], fth, tind % Nsteps, f_ex_vec[ifx]*2*dcpi, *dt, Nsteps);
	}
```

**Comment by samcunliffe** [comment]
Hey Peter.

Good catch. How did you spot it? And can we add some more steady-state testing so that we block such a thing from happening again?

> What’s the best was to make this change on the TDSM repository. It’s a relatively simple update

Best is to create a new bugfix branch from main, then push and make a pull request. (Even for simple updates it's a good habit.) If you know how to do this then please ignore me. If not, here's a brief recipe:

```bash
git status
git branch # no arguments just to see where you are
git checkout main  # if you're not there already
git pull # get all changes from the github version
git checkout -b peters-fix-stead-state 
# 👆 creates a new branch from the latest main and checks out that branch...
git branch # just to verify what happened
# then fix the code...
emacs -nw tdms/src/iterator.cpp
# check it builds ok
cd tdms/build; cmake ..; make install; cd ../.. 
# ... and run any other tests you like before pushing...
git push origin peters-fix-stead-state
```

Now, when you return to GitHub, you should see a green banner in the web GUI about the new branch that you've just pushed. There's probably a button "create pull request" or something. If not go to [the pull requests tab](https://github.com/UCL/TDMS/pulls) → "Create new pull request" → Choose the branch drop-downs for `UCL/main` <- `UCL/peters-fix-steady-state`. Probably best to add Will as a reviewer. 

He'll either approve or comment or whatever, and Github automatically verifies all of our tests pass with this change. Then when you get the green tick of approval, you can merge.

[Hope those instructions are helpful and not too obvious.]

**Comment by prmunro** [comment]
Thanks @samcunliffe , I found this bug because I knew this feature in the code hasn't been used for > 10 years, so I wanted to check it worked still. In theory pulsed and steady state should have the same behaviour. From a transfer function point of view, the steady state case is like having a Dirac delta as the input (in the frequency domain) and we wait until the solution has stabilised, whereas the pulsed case has a Gaussian as the input, and we just pick out the central frequency. Since it is a Gaussian we don't have erroneous high frequencies introduced, and so there is no time required for these to decay.

**Comment by prmunro** [comment]
@samcunliffe , I followed your instructions above, however, within the git gui, it says that "main and peters-fix-stead-state are identical". However, I see the following output, am I missing a step? Sorry if I'm missing something obvious!

pmunro@PMPC03:~/code/FDTD/ARC/TDMS2/TDMS$ git status
On branch peters-fix-stead-state
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   tdms/src/electric_field.cpp
	modified:   tdms/src/iterator.cpp

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by samcunliffe** [comment]
> @samcunliffe , I followed your instructions above, however, within the git gui, it says that "main and peters-fix-stead-state are identical". However, I see the following output, am I missing a step? Sorry if I'm missing something obvious!
> 
> pmunro@PMPC03:~/code/FDTD/ARC/TDMS2/TDMS$ git status On branch peters-fix-stead-state Changes not staged for commit: (use "git add ..." to update what will be committed) (use "git restore ..." to discard changes in working directory) modified: tdms/src/electric_field.cpp modified: tdms/src/iterator.cpp
> 
> no changes added to commit (use "git add" and/or "git commit -a")

Oups! I gave incomplete instructions. Yes you need to add the files you changed or `git add -u`.
Looks like you need to `git add  tdms/src/electric_field.cpp  tdms/src/iterator.cpp` then `git commit -m "Meaningful commit message"`.

Instructions updated 🤦 . My bad.

**Comment by prmunro** [comment]
Thanks Sam, no problem. I believe I have now been able to follow these instructions and have created a pull request.

**Comment by prmunro** [comment]
> @samcunliffe , I followed your instructions above, however, within the git gui, it says that "main and peters-fix-stead-state are identical". However, I see the following output, am I missing a step? Sorry if I'm missing something obvious!
> 
> pmunro@PMPC03:~/code/FDTD/ARC/TDMS2/TDMS$ git status On branch peters-fix-stead-state Changes not staged for commit: (use "git add ..." to update what will be committed) (use "git restore ..." to discard changes in working directory) modified: tdms/src/electric_field.cpp modified: tdms/src/iterator.cpp
> 
> no changes added to commit (use "git add" and/or "git commit -a")

Hi @samcunliffe , I found a bug in the branch of peters-fix-stead-state, how do I update this code given that the previous update hasn't been accepted? I would like to overwrite the previous update. 

Thanks - Peter

**Comment by samcunliffe** [comment]
> Hi @samcunliffe , I found a bug in the branch of peters-fix-stead-state, how do I update this code given that the previous update hasn't been accepted? I would like to overwrite the previous update.

Ah, no problem. Actually, you can "just" push another commit and then squash when merging.
```
git status
git branch # find out where you are
git checkout peters-fix-stead-state # if you're not already on it
emacs -nw file.cpp # fix the problem
git add file.cpp # or git add -u # grabs all changed files
git status # check the fixed files are green
git commit -m "Short explanation... "
git push # should work by default you might need to ...
#git push --set-upstream=origin/peters-fix-stead-state # or something similar
```

Then when all is settled and you have approval on the PR, click the button "Squash and merge" which squashes all changes to one commit.

**Comment by samcunliffe** [comment]
I should also say, [you can try `git diff`](https://git-scm.com/docs/git-diff) (up, down arrows then q to quit). It should be a bit more colourful and helpful if you want to double-check whatever changes are w.r.t the last committed version.

**Comment by prmunro** [comment]
Thanks Sam, the above instructions worked. I believe the forks can now be merged.
